### ISSUE TITLE
Provide overridden Client API without workflowRunId required 

### ISSUE THREAD

**Issue by longquanzheng** [indeedeng/iwf-java-sdk#183]
Even putting an empty string as workflowRunId is unnecessary

**Comment by zklgame** [comment]
Quick question: is there any Client public API must have the runId?

**Comment by longquanzheng** [comment]
> Quick question: is there any Client public API must have the runId?

Technically, all the api may need it if want to call the api on the previous one with the same workflowID. 

For example, read only RPC can still be called on older run to get some data. 

However, the runID could be tricky to get because of auto continue as new , unless 
* user use “searchWorkflow” api to get the last one of the “continueAsNew chain” before calling it 
* Or disabling the auto continue as new (override the threshold to zero)

**Comment by longquanzheng** [comment]
> user use “searchWorkflow” api to get the last one of the “continueAsNew chain” before calling it

I just opened a ticket https://github.com/indeedeng/iwf/issues/306 to have a separate API for this

**Comment by zklgame** [comment]
in #185
