### ISSUE TITLE
[breaking change]Fix wrong API names GetDataObjects

### ISSUE THREAD

**Issue by longquanzheng** [indeedeng/iwf-java-sdk#186]
As part of the major version upgrade, the name should be changed to `GetDataAttributes`...

https://github.com/indeedeng/iwf-java-sdk/releases/tag/v2.0.0

Now we have to make another breaking changes 🤦

**Comment by zklgame** [comment]
Should we change the sdk-idl first?
https://github.com/indeedeng/iwf-idl/pull/44/files

**Comment by longquanzheng** [comment]
> Should we rename in the sdk-idl now? https://github.com/indeedeng/iwf-idl/pull/44/files

That will be too much to do for this ticket, related to a lot of change in public repo and internal repos. We could do that in the future

**Comment by zklgame** [comment]
in #189
